// Extension for Google Chrome - Click&Clean - Copyright (c) 2013 HOTCLEANER.COM - All Rights Reserved
window.addEventListener("load",function(){function j(a){a==p?p=-9:chrome.windows.getAll({},function(a){0==a.length&&setTimeout(q,1E3)})}function q(){chrome.windows.create({url:"cc.html",type:"popup",top:20,left:screen.width-340,width:300,height:8},function(a){p=a.id})}function g(a){a?chrome.windows.onRemoved.addListener(j):chrome.windows.onRemoved.removeListener(j)}function h(){localStorage.setItem("opt",JSON.stringify(b))}function t(){chrome.tabs.create({url:"http://www.hotcleaner.com/clickclean/install.html"})}
function r(a,b){if(0==a.menuItemId)chrome.history.deleteUrl({url:b.url},function(){var a=b.url,e=function(){c++;c<d.length?chrome.cookies.remove({url:a,name:d[c].name},e):chrome.tabs.executeScript(b.id,{file:"safe.js"})},d,c=-1;chrome.cookies.getAll({url:a},function(a){d=a;e()})});else if(1==a.menuItemId){var d=a.linkUrl,e=d.indexOf("&url="),c;0<e&&(c=d.indexOf("&",e+5),d=decodeURIComponent(d.slice(e+5,c)));chrome.tabs.create({url:d})}else 2==a.menuItemId&&chrome.tabs.create({url:"https://encrypted.google.com/search?q="+
encodeURIComponent(a.selectionText)+"&tbo=1"})}function B(a){if(a){var b=chrome.i18n.getMessage("ctxMenu").split(";");chrome.contextMenus.create({id:"0",title:b[0],contexts:["page"]},function(){chrome.contextMenus.create({id:"1",title:b[1],contexts:["link"]},function(){chrome.contextMenus.create({id:"2",title:b[2],contexts:["selection"]},function(){chrome.contextMenus.onClicked.addListener(r)})})})}else chrome.contextMenus.onClicked.removeListener(r),chrome.contextMenus.removeAll()}function C(a){chrome.tabs.onCreated[a?
"addListener":"removeListener"](s);chrome.tabs.onUpdated[a?"addListener":"removeListener"](s)}function s(a,b,d){a=d?d:a;b=a.url;0==b.indexOf(v)&&7<b.indexOf("/history/")&&chrome.tabs.update(a.id,{url:v+"newtab"})}function D(a){a==n&&(chrome.windows.onRemoved.removeListener(D),n=-9)}function E(a,H,d){b.p4&&w();chrome.browsingData.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,
pluginData:!!b.p12,serverBoundCertificates:H?!1:!!b.p4},function(){chrome.browsingData.remove({since:a},{downloads:!!b.p2},function(){b.dev?chrome.browsingData.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!b.p13,localStorage:!!b.p14,webSQL:!!b.p15,indexedDB:!!b.p16,fileSystems:!!b.p17,appcache:!!b.p18},function(){chrome.browsingData.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!b.p19,localStorage:!!b.p20,webSQL:!!b.p21,
indexedDB:!!b.p22,fileSystems:!!b.p23,appcache:!!b.p24},function(){b.p20&&h();d()})}):d()})})}function w(a){var b=a?a:x(),d;chrome.cookies.getAll({},function(a){a.forEach(function(a){d=a.domain;"."==d.charAt(0)&&(d=d.slice(1));0>b.indexOf(d)&&chrome.cookies.remove({url:"http"+(a.secure?"s":"")+"://"+d+a.path,name:a.name})})})}function x(){var a=localStorage.getItem("wl");if(void 0==a)return[];try{a=JSON.parse(a)}catch(b){a=[]}return a}function y(){var a=b.timeType;return 10==a?0:0==a?z:9==a?b.time:
(new Date).getTime()-36E5*[0,1,2,4,8,10,12,24,168][a]}var z=(new Date).getTime(),v=/Comodo/.test(navigator.appVersion)?"dragon://":"chrome://",f,n=-9,p=-9,b={ver:"8.3",nv:0,timeType:10,time:0,dev:0,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:1,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0};a:{var c=localStorage.getItem("opt");if(void 0==c)h(),t();else{try{c=JSON.parse(c)}catch(J){h();break a}if("8.3"!=c.ver){for(var l in c)void 0!=
b[l]&&(b[l]=c[l]);b.ver="8.3";b.nv=7;h()}else b=c,1<b.nv&&(c=new Uint8Array(1),crypto.getRandomValues(c),c[0]<b.nv?(b.nv=0,h(),t()):(b.nv+=parseFloat(b.nv)/12,h()))}b.p26&&(0==b.timeType?(c=parseInt(localStorage.getItem("s0")),localStorage.setItem("s0",z)):c=y(),E(c,1,function(){g(1)}));b.p29&&B(1);b.p30&&C(1)}chrome.extension.onRequest.addListener(function(a,c,d){var e;try{e=JSON.parse(a)}catch(j){return}a=e.id;if(0==a)if(-9==n){c=600<screen.height?463:430;a=parseInt((screen.height-c)/2);var k=parseInt((screen.width-
760)/2);chrome.windows.create({url:"cleaner.html",width:760,height:c,top:a,left:k,type:"popup",focused:!0},function(a){n=a.id;chrome.windows.onRemoved.addListener(D)})}else chrome.windows.update(n,{focused:!0});else if(1==a){a=b;c=c.tab.url;a:{try{chrome.browsingData.removePluginData({originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!1}})}catch(p){k=0;break a}k=1}d({v:a,u:c,d:k,t:z})}else if(2==a)d(c.tab.url);else if(3==a)d(b);else if(4==a)q();else if(5==a){var l=function(a){if(e.v1){var b=
new FileReader;b.onload=function(a){d(a.target.result)};b.readAsDataURL(a)}else{var c=window.webkitURL.createObjectURL(a);d(c);setTimeout(function(){window.webkitURL.revokeObjectURL(c)},1E3)}};c=new XMLHttpRequest;c.open("GET",e.v,!0);c.responseType="blob";c.onload=function(){200==this.status?l(this.response):l(0)};c.send()}else if(6==a){c=e.v;a=e.v2;var k=e.v3,u=0;if(!f){f=document.createElement("EMBED");f.type="application/x-mixesoft";document.body.appendChild(f);try{u=f.cmd(c,a,k)}catch(t){u=0}f=
document.body.removeChild(f)}f=null;d(u)}else if(7==a)b.p26!=e.v.p26?g(e.v.p26):b.p29!=e.v.p29?B(e.v.p29):b.p30!=e.v.p30&&C(e.v.p30),b=e.v,h();else if(8==a){var r=e.v2,s=e.v3,F=function(){chrome.tabs.get(A,function(a){"complete"==a.status?0>a.title.indexOf(r)&&chrome.tabs.update(A,{url:s}):setTimeout(F,100)})},A;chrome.tabs.create({url:e.v},function(a){chrome.windows.update(a.windowId,{focused:!0});A=a.id;F()})}else if(9==a)chrome.tabs.create({url:e.v},function(a){chrome.windows.update(a.windowId,
{focused:!0})});else if(10==a)chrome.history.deleteUrl(e.v,d);else if(11==a)chrome.history.deleteRange(e.v,d);else if(12==a)chrome.history.search(e.v,d);else if(13==a)chrome.history.getVisits(e.v,d);else if(14==a)chrome.tabs.update(c.tab.id,{url:v+"newtab"},function(){chrome.history.deleteUrl(e.v)});else if(18==a)c=y(),E(c,0,function(){d(b.p28)});else if(19==a)0>e.v.since&&(e.v.since=y()),e.v2.cookies?(w(),d(b.p28)):chrome.browsingData.remove(e.v,e.v2,function(){d(b.p28)});else if(30==a){var I=x(),
G=[];chrome.cookies.getAll({},function(a){for(var b=0,c;c=a[b];b++)G.push(c.domain);d([G,I])})}else if(31==a)w();else if(32==a){var m;e.v.forEach(function(a){chrome.cookies.getAll({domain:a},function(b){b.forEach(function(b){m=b.domain;"."==m.charAt(0)&&(m=m.slice(1));m==a&&chrome.cookies.remove({url:"http"+(b.secure?"s":"")+"://"+m+b.path,name:b.name})})})})}else 34==a?d(x()):35==a&&localStorage.setItem("wl",JSON.stringify(e.v))})},!1);
function copyToClipboard(j,q){if(!q||prompt("Copy to clipboard",j)){var g=document.createElement("textarea");g.value=j;document.body.appendChild(g);g.select();document.execCommand("Copy");document.body.removeChild(g)}};
