// Extension for Google Chrome - Click&Clean - Copyright (c) 2013 HOTCLEANER.COM - All Rights Reserved
window.addEventListener("load",cacheViewer,!1);
function cacheViewer(){function B(){j(1);y();chrome.extension.sendRequest('{"id":6,"v":3,"v2":1}',function(b){b?(c=b.split("\n"),g(1)):j(0)})}function C(){var b=this.parentElement.getAttribute("data-key");chrome.extension.sendRequest(JSON.stringify({id:9,v:b}))}function D(){var b=this.parentElement.parentElement.getAttribute("data-key");chrome.extension.sendRequest(JSON.stringify({id:9,v:"chrome://view-http-cache/"+b}))}function E(){j(1);chrome.extension.sendRequest('{"id":19,"v":{"since":-1},"v2":{"cache":true}}',function(){y();
j(0)})}function F(){chrome.extension.sendRequest('{"id":6,"v":3,"v2":3,"v3":"'+this.getAttribute("fname")+'"}')}function G(){0<k&&(k--,a=q[k],g(0))}function H(){a<c.length&&(k++,q[k]=a,g(0))}function z(b,c,a,l,f){var e=document.createElement("div"),d=document.createElement("div"),m=document.createElement("div"),k=document.createElement("div"),j=document.createElement("div"),g=document.createElement("div");e.className="item";e.setAttribute("data-ct",a);e.setAttribute("data-b",f);m.className="iftr";
k.className="ibtn idat";j.className="ibtn iexp";g.className="iinf";e.setAttribute("data-key",c);k.title=t[13];e.appendChild(d);e.appendChild(m);e.appendChild(g);"0"!=l&&(j.setAttribute("fname",l),m.appendChild(j),j.title=t[14],j.addEventListener("click",F,!1));m.appendChild(k);m.appendChild(document.createTextNode(I(c)));if(-1<a.search(/image/)&&524288>f){var s=new Image,r,p,q,v;s.onload=function(){r=this.width;p=this.height;0<r&&0<p?(1024>r&&1024>p?(176<r||110<p?1.6<r/p?(v=parseInt(176*p/r),q=176,
this.style.marginTop=parseInt((110-v)/2)+"px"):(q=parseInt(110*r/p),v=110):(q=r,v=p,this.style.marginTop=parseInt((110-p)/2)+"px"),this.style.width=q+"px",this.style.height=v+"px",d.className="iimg",d.appendChild(s)):(d.className="itxt",d.textContent=a),g.textContent=r+"x"+p+" "+u(f)):(d.className="itxt",d.textContent=a,g.textContent=u(f))};s.src=c}else d.className="itxt",d.textContent=a,g.textContent=u(f);d.addEventListener("click",C,!1);k.addEventListener("click",D,!1);b.appendChild(e)}function g(b){j(1);
var n=d("search").value,h=w.getAttribute("data-ct"),l=document.createDocumentFragment(),f;if(1>n.length)if("/"==h)for(f=0;a<c.length&&!(z(l,c[a],c[a+1],c[a+2],c[a+3]),f++,a+=4,f==x););else{f=0;for(var e;a<c.length&&!(e=c[a+1],-1<e.indexOf(h)&&(z(l,c[a],c[a+1],c[a+2],c[a+3]),f++),a+=4,f==x););}else{f=0;for(var g;a<c.length&&!(e=c[a],g=c[a+1],-1<e.indexOf(n)&&-1<g.indexOf(h)&&(z(l,c[a],c[a+1],c[a+2],c[a+3]),f++),a+=4,f==x););}d("content").textContent="";d("content").appendChild(l);if(b)if(1>n.length)if("/"==
h){n=h=0;for(b=3;b<c.length;b+=4)n+=parseInt(c[b]),h++;s=h+" items / "+u(n)}else{for(e=l=n=0;e<c.length;e+=4)b=c[e+1],-1<b.indexOf(h)&&(l+=parseInt(c[e+3]),n++);s=n+" items / "+u(l)}else{for(var m=g=b=0;m<c.length;m+=4)l=c[m],e=c[m+1],-1<l.indexOf(n)&&-1<e.indexOf(h)&&(g+=parseInt(c[m+3]),b++);s=b+" items / "+u(g)}h=k*x;f=h+f;d("info").textContent=h+"-"+f+" of "+s;d("prev").style.opacity=1>h?0.5:1;d("next").style.opacity=f==parseInt(s)?0.5:1;d("info2").textContent=k+1;d("tab").scrollTop=0;j(0)}function y(){k=
a=0;q=[0];c=[];d("info").textContent="0 items / 0 MB";d("info2").textContent="-";d("content").textContent=t[15];d("next").style.opacity=d("prev").style.opacity=0.5}function A(){k=a=0;q=[0];this.hasAttribute("data-ct")&&(w.className="btn nav",this.className="btn nav on",w=this);g(1)}function u(b){return 1048577>b?(b/1024).toFixed(1)+"KB":(b/1048576).toFixed(1)+"MB"}function j(b){d("shade").style.display=b?"block":"none";d("clear").firstElementChild.src=b?"i/wipe.gif":"i/del1.png"}function I(b){var c=
b.indexOf(":")+3,a=b.indexOf("/",c);return b.slice(c,a)}function d(b){return document.getElementById(b)}var c,a=0,q=[0],k=0,x=60,s,w,t=chrome.i18n.getMessage("cache").split(";");chrome.extension.sendRequest('{"id":2}',function(b){j(1);!b.indexOf(0==chrome.extension.getURL(""))&&(0!=b.indexOf("http://www.hotcleaner.com/")&&0!=b.indexOf("http://hotcleaner.com/"))&&(document.location.href="about:blank");b=function(b,c){a.addEventListener("click",c,!1);a.title=t[b];a=a.nextElementSibling};var a;w=a=d("hdr").firstElementChild;
for(var h=0;7>h;h++)b(h,A);b(7,B);b(8,E);a.addEventListener("keyup",A,!1);a.setAttribute("placeholder",t[9]);a=d("prev");b(10,G);a.title=t[11];a=a.nextElementSibling;b(12,H);chrome.extension.sendRequest('{"id":6,"v":3,"v2":1}',function(a){a?(c=a.split("\n"),g(1)):(y(),j(0))})})};
