// Extension for Google Chrome - Click&Clean - MIT 2013 HOTCLEANER.COM
var CALCONF={},CALTOKENS=[],CALTOKENS_IDX={};
function calInit(a,b,c,d){var f=chrome.i18n.getMessage("calendar").split(";");CALCONF.months=f.slice(0,12);CALCONF.weekdays=f.slice(12,19);CALCONF.longwdays=f.slice(19,26);CALCONF.weekstart=0;CALCONF.prevyear=f[26];CALCONF.nextyear=f[27];CALCONF.prevmonth=f[28];CALCONF.nextmonth=f[29];CALCONF.today=f[30];CALCONF.cancel=f[31];CALTOKENS.push({t:"l",r:CALCONF.longwdays.join("|"),p:function(a){return a},g:function(a){return CALCONF.longwdays[a.getDay()]}},{t:"Y",r:"19\\d{2}|20\\d{2}",p:function(a,c){a.setFullYear(Number(c));
return a},g:function(a){return a.getFullYear()}},{t:"F",r:CALCONF.months.join("|"),p:function(a,c){for(var b=0;12>b;b++)if(CALCONF.months[b]==c)return a.setMonth(b),a},g:function(a){return CALCONF.months[a.getMonth()]}},{t:"d",r:"0[1-9]|[12][0-9]|3[01]",p:function(a,b){a.setDate(Number(b));a.getDate()!=b&&a.setDate(0);return a},g:function(a){a=a.getDate();return(10>a?"0":"")+a}},{t:"h",r:"[0-1][0-9]|2[0-3]",p:function(a,b){a.setHours(Number(b));a.getHours()!=b&&a.setHours(0);return a},g:function(a){a=
a.getHours();return(10>a?"0":"")+a}},{t:"e",r:"[0-4][0-9]|5[0-9]",p:function(a,b){a.setMinutes(Number(b));a.getMinutes()!=b&&a.setMinutes(0);return a},g:function(a){a=a.getMinutes();return(10>a?"0":"")+a}},{t:"s",r:"[0-4][0-9]|5[0-9]",p:function(a,b){a.setSeconds(Number(b));a.getSeconds()!=b&&a.setSeconds(0);return a},g:function(a){a=a.getSeconds();return(10>a?"0":"")+a}});for(f=0;f<CALTOKENS.length;f++)CALTOKENS_IDX[CALTOKENS[f].t]=CALTOKENS[f];a.onDateChanged=d;a.showTime=c;calSetDate(a,b?new Date(b):
new Date);a.oncut=function(a){a.returnValue=!1};a.oncontextmenu=function(a){a.returnValue=!1};a.ondragstart=function(a){a.returnValue=!1};a.onkeydown=function(a){this.nextElementSibling.focus();a.returnValue=!1};a.onclick=function(a){a.returnValue=!1};a.addEventListener("mouseup",calMouseup,!1);c&&(a.nextElementSibling.addEventListener("mousedown",calOnSpinDown,!1),a.nextElementSibling.addEventListener("mouseup",calOnSpinUp,!1),a.nextElementSibling.nextElementSibling.addEventListener("mousedown",
calOnSpinDown,!1),a.nextElementSibling.nextElementSibling.addEventListener("mouseup",calOnSpinUp,!1))}function calSetDate(a,b){a.showTime||(b=calResetTime(b));var c=b.getTime();a.setAttribute("data-time",c);a.value=calGenerateDate(b,a.getAttribute("data-format"));a.onDateChanged(c)}function calClose(){$("cal").style.display="none"}function calSetToday(){calSetDate(this.parentElement.e_input,new Date);calClose()}
function calParseDate(a,b){for(var c,d="^",f={},m=0,j=0;j<b.length;j++)c=b.charAt(j),CALTOKENS_IDX[c]?(f[c]=++m,d+="("+CALTOKENS_IDX[c].r+")"):d=" "==c?d+"\\s":d+((c.match(/[\w\d]/)?"":"\\")+c);if(!a.match(RegExp(d+"$")))return 0;d=new Date;d.setDate(1);for(j=0;j<CALTOKENS.length;j++)c=CALTOKENS[j].t,f[c]&&(c=RegExp["$"+f[c]],d=CALTOKENS[j].p(d,c));return d}
function calGetHTML(a){function b(a,b,c,d){var e=document.createElement("button");b&&(e.className=b);e.textContent=c;a.appendChild(e);e.addEventListener("click",d,!1)}function c(a,b){var c=document.createElement("div");c.className="arrow"+(b?"Left":"Right");c.style.display="inline-block";a.appendChild(c)}var d=$("cal"),f=d.e_input,m=f.getAttribute("data-format"),j=new Date,m=calParseDate(f.value,m);a||(a=m);f.showTime||(a=calResetTime(a));f=new Date(a);f.setDate(1);f.setDate(1-(7+f.getDay()-CALCONF.weekstart)%
7);var g,n=document.createDocumentFragment(),l,h,e;l=document.createElement("table");l.id="calCtrls";h=document.createElement("tr");l.appendChild(h);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.prevyear;e.time=calRelDate(a,-1,"FullYear");e.addEventListener("click",calUpdate,!1);h.appendChild(e);c(e,1);c(e,1);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.prevmonth;e.time=calRelDate(a,-1,"Month");e.addEventListener("click",calUpdate,!1);h.appendChild(e);
c(e,1);e=document.createElement("th");e.textContent=CALCONF.months[a.getMonth()]+" "+a.getFullYear();h.appendChild(e);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.nextmonth;e.time=calRelDate(a,1,"Month");e.addEventListener("click",calUpdate,!1);h.appendChild(e);c(e,0);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.nextyear;e.time=calRelDate(a,1,"FullYear");e.addEventListener("click",calUpdate,!1);h.appendChild(e);c(e,0);c(e,0);n.appendChild(l);l=document.createElement("table");
l.id="calGrid";h=document.createElement("tr");l.appendChild(h);for(g=0;7>g;g++)e=document.createElement("th"),e.textContent=CALCONF.weekdays[(CALCONF.weekstart+g)%7],h.appendChild(e);for(var p,q,k=new Date(f);k.getMonth()==a.getMonth()||k.getMonth()==f.getMonth();){h=document.createElement("tr");for(var r=0;7>r;r++){g=[];p=k.getDate();e=k.getMonth();q=k.getYear();k.getMonth()!=a.getMonth()&&(g[g.length]="calOtherMonth");if(0==k.getDay()||6==k.getDay())g[g.length]="calWeekend";q==j.getYear()&&(e==
j.getMonth()&&p==j.getDate())&&(g[g.length]="calToday");q==m.getYear()&&(e==m.getMonth()&&p==m.getDate())&&(g[g.length]="calSelected");e=document.createElement("td");e.textContent=p;e.className=g.join(" ");e.time=calRelDate(k);h.appendChild(e);e.addEventListener("click",calUpdate,!1);k.setDate(++p)}l.appendChild(h)}n.appendChild(l);b(n,"calBtn",CALCONF.today,calSetToday);b(n,"calBtn",CALCONF.cancel,calClose);d.innerHTML="";d.appendChild(n)}
function calRelDate(a,b,c){var d=new Date(a);b&&(d["set"+c](a["get"+c]()+b),d.getDate()!=a.getDate()&&d.setDate(0));return d.valueOf()}function calUpdate(){var a=document.getElementById("cal"),b=a.e_input,c=this.time,d=new Date(c);"calCtrl"==this.className?calGetHTML(d,a):(b.value=calGenerateDate(d,b.getAttribute("data-format")),b.setAttribute("data-time",c),b.onDateChanged(c),a.style.display="none")}
function calOnDateChanged(a){var b=calParseDate(a.value,a.getAttribute("data-format"));a.onDateChanged(b.getTime())}function calGenerateDate(a,b){for(var c,d="",f=0;f<b.length;f++)c=b.charAt(f),d+=CALTOKENS_IDX[c]?CALTOKENS_IDX[c].g(a):c;return d}function calOnSpinDown(){var a=this.parentElement.firstElementChild;a.repeat=1E3;a.up="calUp"==this.className?1:0;calOnSpin(a)}function calOnSpinUp(){var a=this.parentElement.firstElementChild;a.repeat=0;calOnDateChanged(a)}
function calOnSpin(a){var b=a.repeat;if(b){1E3==b?b-=801:200>b&&(b-=25);100>b&&(b=100);a.repeat=b;var c=a.value.indexOf("-");a.selStart||(a.selStart=c+2);var d=a.value.slice(a.selStart,a.selStart+2),d="0"==d.charAt(0)?parseInt(d.charAt(1)):parseInt(d),d=a.up?d+1:d-1;a.selStart==c+2?23<d?d="00":0>d?d="23":10>d&&(d="0"+d):59<d?d="00":0>d?d="59":10>d&&(d="0"+d);a.value=a.value.slice(0,a.selStart)+d+a.value.slice(a.selStart+2);setTimeout(calOnSpin,b,a)}}
function calOnTime(a){var b=a.value.indexOf("-"),c=a.selectionStart;if(c>b)return c<b+5?c=b+2:c<b+8?c=b+5:c<b+12&&(c=b+8),a.selStart=c,a.setSelectionRange(c,c+2),1;a.setSelectionRange(0,b-1);return 0}
function calMouseup(){var a=document.getElementById("cal"),b=$XY(this);a||(a=document.createElement("button"),a.onselectstart=function(){return!1},a.id="cal",document.body.appendChild(a));if(this.showTime){if(calOnTime(this)){a.style.display="none";return}}else this.blur();0<a.offsetHeight&&a.e_input==this?a.style.display="none":(a.e_input=this,a.style.display="block",calGetHTML(0,a),a.style.top=b[1]+this.offsetHeight+"px",a.style.left=b[0]+"px",a.style.display="block",a.focus())}
function calResetTime(a){a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a}function $XY(a){if(a&&void 0!=a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[b,c]}}function $(a){return document.getElementById(a)};
