// Extension for Google Chrome - Click&Clean - Copyright (c) 2013 HOTCLEANER.COM - All Rights Reserved
window.addEventListener("load",function(){function m(){chrome.extension.sendRequest(JSON.stringify({id:7,v:d}))}function B(){function a(){e.className="ghk";h(0==c||25==c||27==c||28==c?"m8":"m7");28!=c&&d.p28&&r();g(0,0);setTimeout(function(){e.className="chk"},1E3)}h();g(1,1);var b=w(),c=parseInt(this.parentElement.firstElementChild.id.slice(1)),e=f("p"+c);5==c&&!confirm(chrome.i18n.getMessage("m11"))?g(0,0):(e.className="wipe",28==c?r(a):x(c,b,a))}function C(){function a(a){for(var b,c=0,e=l.length;c<
e;c++)b=f("p"+l[c]),b.hasAttribute("on")&&(b.className=a)}function b(){setTimeout(function(){f("p"+l[p]).className="ghk";c()},10)}function c(){p++;if(p<l.length){var f=l[p];d["p"+f]?28==f?(h("m7"),r(b)):x(f,e,b):c()}else h("m7"),setTimeout(function(){a("chk");g(0,0)},700)}h();g(1,1);var e=w(),p=-1,l;l=n&&d.dev?[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,28,27]:[0,1,2,3,4,5,6,7,8,9,10,11,12,25,28,27];a("wipe");c()}function x(a,b,c){var e=chrome.browsingData,d={since:b};13>
a?0==a?y(0,c):1==a?e.removeHistory(d,c):2==a?e.removeDownloads(d,function(){e.removeDownloads(d,c)}):3==a?e.removeCache(d,c):4==a?e.remove(d,{serverBoundCertificates:!0},function(){chrome.extension.sendRequest('{"id":31}');c()}):5==a?e.removePasswords(d,c):6==a?e.removeFormData(d,c):7==a?e.removeLocalStorage(d,c):8==a?e.removeWebSQL(d,c):9==a?e.removeIndexedDB(d,c):10==a?e.removeFileSystems(d,c):11==a?e.removeAppcache(d,c):12==a&&e.removePluginData(d,c):19>a?(d.originTypes={unprotectedWeb:!1,protectedWeb:!0,
extension:!1},13==a?e.removeCookies(d,c):14==a?e.removeLocalStorage(d,c):15==a?e.removeWebSQL(d,c):16==a?e.removeIndexedDB(d,c):17==a?e.removeFileSystems(d,c):18==a&&e.removeAppcache(d,c)):25>a?(d.originTypes={unprotectedWeb:!1,protectedWeb:!1,extension:!0},19==a?e.removeCookies(d,c):20==a?e.removeLocalStorage(d,function(){m();c()}):21==a?e.removeWebSQL(d,c):22==a?e.removeIndexedDB(d,c):23==a?e.removeFileSystems(d,c):24==a&&e.removeAppcache(d,c)):25==a?y(1,c):27==a?window.close():c()}function y(a,
b){chrome.windows.getCurrent(function(c){chrome.tabs.query(a?{active:!0}:{},function(e){var d=0;e.forEach(function(f,g){f.windowId!=c.id?a?chrome.tabs.reload(f.id):g>d?chrome.tabs.remove(f.id):chrome.tabs.update(f.id,{url:/Comodo/.test(navigator.appVersion)?"dragon://newtab":"chrome://newtab"}):0==g&&(d=1);b&&g==e.length-1&&setTimeout(b,a?200:2E3)})})})}function D(){var a=parseInt(this.previousElementSibling.id.slice(1)),b=[7,8,9,10,13,14,15,16,17,19,20,21,22,23],c=/Comodo/.test(navigator.appVersion)?
"dragon://":"chrome://";if(1==a)q("http://www.hotcleaner.com/clear-browsing-history.html","Clear","history.html");else{if(2==a)c+="downloads/";else if(3==a){if(/Win/.test(navigator.platform)){q("http://www.hotcleaner.com/cache-viewer.html","Cache","cache.html");return}c+="cache"}else{if(4==a){q("http://www.hotcleaner.com/cookie-wiper.html","Cookie","cookies.html");return}-1<b.indexOf(a)?c+="settings/cookies":5==a?c+="settings/passwords":6==a?c+="settings/autofill":11==a||18==a||24==a?c+="appcache-internals":
12==a&&(c+="plugins")}chrome.extension.sendRequest(JSON.stringify({id:9,v:c}))}}function z(a){var b=f("textMetrics");b.textContent=a;return b.offsetWidth}function E(a){d.time=a;m()}function s(){var a=f("timeType"),b=a.selectedIndex;d.timeType=b;a.style.width=z(a.value)+40+"px";A();0==b&&localStorage.setItem("s0",t);m()}function A(){var a=f("time");if(9==d.timeType)a.firstElementChild.hasAttribute("data-time")||calInit(a.firstElementChild,d.time,1,E),a.style.display="",f("timeType").style.width="1px";
else if(a.style.display="none",a=f("cal"))a.style.display="none"}function w(){var a=d.timeType;return 10==a?0:0==a?t:9==a?d.time:(new Date).getTime()-36E5*[0,1,2,4,8,10,12,24,168][a]}function F(a){if(this.hasAttribute("on"))this.removeAttribute("on"),d[this.id]=0;else{if("p5"==this.id&&!confirm(chrome.i18n.getMessage("m10")))return a.preventDefault(),!1;this.setAttribute("on",!0);d[this.id]=1}m()}function g(a,b){var c=f("clear");f("shade").style.display=a?"block":"none";b?c.setAttribute("on",!0):
c.removeAttribute("on")}function h(a){var b=f("msg");a?(b.textContent=chrome.i18n.getMessage(a),b.style.left=(f("page").offsetWidth-b.offsetWidth)/2+"px",b.style.top="42px",setTimeout(h,2E3)):b.style.top=""}function j(){var a=this.id;encodeURIComponent("https://chrome.google.com/webstore/detail/ghgabhipcejejjmhhchfonmamedcbeod");var b;if("logo"==a)b="http://www.hotcleaner.com/";else if("fox"==a){if(b="https://addons.mozilla.org/en-us/firefox/addon/clickclean/",/Win/.test(navigator.platform)){chrome.extension.sendRequest('{"id":6,"v":202}',
function(a){a||chrome.extension.sendRequest('{"id":9,"v":"'+b+'"}')});return}}else"ctrb"==a?b="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=webmaster@mixesoft.com&item_name=Contribution for Click and Clean&no_note=1&no_shipping=1&country=US&currency_code=USD":"ghist"==a?b="https://history.google.com/history/settings?st=tr":"sync"==a?b="https://www.google.com/settings/chrome/sync":"ssl"==a&&(b="http://www.hotcleaner.com/secure_search.html");chrome.extension.sendRequest('{"id":9,"v":"'+
b+'"}')}function u(){var a=f("dev");a.style.display=n?"":"none";if(n){for(var b=document.getElementsByClassName("dev"),c=n?d.dev?"":"none":"none",e=0;e<b.length;++e)b[e].style.display=c;d.dev?a.setAttribute("on",!0):a.removeAttribute("on")}}function G(){d.dev=d.dev?0:1;u();m();d.dev&&alert(chrome.i18n.getMessage("m3"))}function v(){h();g(1,0);var a;a=this.id;var b;if("reset0"==a)b=[10,0,0,1,1,1,0,0,0,0,0,0,0,0,0];else if("reset1"==a)b=[10,0,0,1,1,1,0,0,1,0,1,1,1,1,1];else if("reset2"==a){if(!d.p5&&
!confirm(chrome.i18n.getMessage("m10"))){g(0,0);return}b=[10,0,0,1,1,1,1,1,1,1,1,1,1,1,1]}d.timeType=b[0];d.p1=b[3];d.p2=b[4];d.p3=b[5];d.p4=b[6];d.p5=b[7];d.p6=b[8];d.p7=b[9];d.p8=b[10];d.p9=b[11];d.p10=b[12];d.p11=b[13];d.p12=b[14];f("timeType").selectedIndex=d.timeType;s();for(b=0;15>b;b++)a=f("p"+b),d[a.id]?a.setAttribute("on",!0):a.removeAttribute("on");g(0,0)}function r(a){(new Audio("erased.ogg")).play();setTimeout(a,800)}function q(a,b,c){g(1,0);h("h7");chrome.extension.sendRequest('{"id":8,"v":"'+
a+'","v2":"'+b+'","v3":"'+c+'"}');g(0,0)}function H(){chrome.extension.sendRequest('{"id":34}',function(a){var b;a=JSON.stringify({opt:d,wl:a});Blob?b=new Blob([a],{type:"application/json;charset=UTF-8"}):BlobBuilder&&(b=new BlobBuilder,b.append(a),b=b.getBlob("application/json;charset=UTF-8"));a="ClickClean-v"+d.ver+"-Options.json";g(1,0);var c=document.createElement("a"),e=window.webkitURL||window.URL;c.href=e.createObjectURL(b);c.setAttribute("download",a);c.click();setTimeout(function(){e.revokeObjectURL(c.href);
g(0,0)},2E3)})}function I(){var a=f("openAs");a&&document.body.removeChild(a);a=document.createElement("input");a.id="openAs";a.style.display="none";a.type="file";document.body.appendChild(a);a.addEventListener("change",function(a){if((a=a.target.files)&&1==a.length&&16384>a[0].size){var c=new FileReader;c.onload=function(a){a:{a=a.target.result;try{a=JSON.parse(a)}catch(b){h("m12");break a}var c=a.opt,g=d.ver,j=d.nv;if(d.p5||!c.p5||confirm(chrome.i18n.getMessage("m10"))){a.wl&&chrome.extension.sendRequest(JSON.stringify({id:35,
v:a.wl}));for(var k in c)void 0!=d[k]&&(d[k]=c[k]);d.ver=g;d.nv=j;f("timeType").selectedIndex=d.timeType;s();for(k=0;31>k;k++)el=f("p"+k),d[el.id]?el.setAttribute("on",!0):el.removeAttribute("on");u();h("m8")}}};c.readAsText(a[0])}else h("m12")},!1);a.click()}function f(a){return document.getElementById(a)}var d,t,n;chrome.extension.sendRequest('{"id":1}',function(a){var b=a.u;!b.indexOf(0==chrome.extension.getURL(""))&&(0!=b.indexOf("http://www.hotcleaner.com/")&&0!=b.indexOf("http://hotcleaner.com/"))&&
(document.location.href="about:blank");d=a.v;t=a.t;n=a.d;u();var c;document.title=chrome.i18n.getMessage("m2");a=function(a,b,c,d,e){a=f(a);b&&("web"==a.className?a.firstElementChild.textContent=b:a.textContent=b);c&&(a.title=c);-1<e&&(a.sid=e,a.style.backgroundImage="url(i/s"+e+".png)");d&&a.addEventListener("click",d,!1)};b=chrome.i18n.getMessage("cleaner1").split(";");chrome.i18n.getMessage("share").split(";");var e=new Uint8Array(1);crypto.getRandomValues(e);e=e[0]%7;a("logo","v"+d.ver,0,j);a("fox",
"Get for Firefox!",0,j);a("ctrb",b[0],b[2],j);a("clear",b[3],0,C);a("hist",b[4],b[5],function(){q("http://www.hotcleaner.com/clear-browsing-history.html","Clear","history.html")});a("support",b[6]);a("help",b[7]);a("reset0",b[8],b[13],v);a("reset1",b[9],b[13],v);a("reset2",b[10],b[13],v);a("dev",b[11],b[12],G);a("export",b[14],0,H);a("import",b[15],0,I);a("ghist",b[16],b[16],j);a("sync",b[17],b[17],j);a("ssl","Enable secure search over SSL",0,j);a=chrome.i18n.getMessage("cleaner2").split(";");b=document.getElementsByClassName("section");
for(e=0;3>e;e++)b[e].childNodes[0].textContent=a[e];b=document.getElementsByClassName("subtitle");for(e=0;3>e;e++)b[e].textContent=a[e+3];b=f("timeType");a=chrome.i18n.getMessage("cleaner3").split(";");f("timeLabel").textContent=a[0];for(e=1;12>e;e++)c=document.createElement("option"),c.textContent=a[e],b.appendChild(c);b.selectedIndex=d.timeType;b.style.width=z(b.value)+40+"px";b.addEventListener("change",s,!1);A();a=chrome.i18n.getMessage("cleaner4").split(";");c=chrome.i18n.getMessage("cleaner5").split(";");
for(e=0;31>e;e++){b=f("p"+e);d[b.id]&&b.setAttribute("on",!0);b.addEventListener("click",F,!1);b=b.nextElementSibling;"optMore"==b.className&&(b.title=c[0],b.addEventListener("click",D,!1),b=b.nextElementSibling);if("optRun"==b.className||"optDel"==b.className)b.title=0==e?c[1]:25==e?c[2]:26==e?c[3]:27==e?c[4]:28==e?c[5]:a[e],b.addEventListener("click",B,!1),b=b.nextElementSibling;b.textContent=b.title=a[e]}})},!1);
