// Extension for Google Chrome - Click&Clean - Copyright (c) 2013 HOTCLEANER.COM - All Rights Reserved
window.addEventListener("load",function(){chrome.extension.sendRequest('{"id":2}',function(m){0==m.indexOf("http://www.hotcleaner.com/")||0==m.indexOf("http://hotcleaner.com/")||0==m.indexOf(chrome.extension.getURL(""))?cookies():document.location.href="about:blank"})},!1);
function cookies(){function m(){n(1);$("list0").innerHTML=$("list1").innerHTML="";chrome.extension.sendRequest('{"id":30}',function(a){var b=a[0];a=a[1];var c=[],g,e,d=0,f=0,j=0;if(0<b.length){for(var l=0,h;h=b[l];l++)"."==h.charAt(0)&&(b[l]=h.slice(1));b.sort(function(a,b){return a<b?-1:1});g=a.indexOf(b[0]);for(l=0;h=b[l];l++)e!=h&&(0<d&&(0>g?(c.push(d),f+=d):(a[g+1]=d,j+=d),d=0),g=a.indexOf(h),0>g&&c.push(h)),d++,e=h;0<d&&(0>g?(c.push(d),f+=d):(a[g+1]=d,j+=d))}y(0,c,1,1);y(1,a,0,0);$("cnt0").textContent=
" ("+f+")";$("cnt1").textContent=" ("+j+")";n(0)})}function z(){for(var a=w(this,"on"),b=this.parentElement.nextElementSibling.children,c=0,g;g=b[c];c++)s(g.firstElementChild,"on",a),s(g,"on",a)}function E(a){var b=this.parentNode.getAttribute("data-domain");chrome.extension.sendRequest('{"id":9,"v":"http://'+b+'"}');a.stopPropagation()}function F(a){a.stopPropagation();a=this.parentNode;var b=a.parentNode.getAttribute("data-id"),c=a.getAttribute("data-domain"),g=parseInt(a.getAttribute("data-count"));
chrome.extension.sendRequest(JSON.stringify({id:32,v:[c]}));a.parentElement.removeChild(a);t(b,-g);1==b&&u()}function u(){for(var a=[],b=$("list1").children,c=0,g;g=b[c];c++)a.push(g.getAttribute("data-domain"),0);chrome.extension.sendRequest(JSON.stringify({id:35,v:a}));n(0)}function A(a,b){var c=$("list"+a).querySelectorAll(".item[on]");if(0<c.length){for(var g=[],e=0,d;d=c[e];e++)g.push(d.parentNode.removeChild(d));B(a,b,g)}}function t(a,b){var c=$("cnt"+a),g=parseInt(c.textContent.slice(2));c.textContent=
" ("+(g+b)+")"}function w(a,b){var c=a.hasAttribute(b);c?a.removeAttribute(b):a.setAttribute(b,!0);return!c}function s(a,b,c){c?a.setAttribute(b,!0):a.removeAttribute(b)}function G(a){var b=this.hasAttribute("on");if(a.shiftKey){if(0>v&&(v=this.parentNode.firstElementChild),a=!b,b=v,this&&b){var c=this;c.getAttribute("data-domain")>b.getAttribute("data-domain")&&(c=b,b=this);for(;c&&c.getAttribute("data-domain")<=b.getAttribute("data-domain");)s(c,"on",a),s(c.firstElementChild,"on",a),c=c.nextElementSibling}}else w(this.firstElementChild,
"on"),w(this,"on");v=this}function C(a,b,c,g){var e,d,f,j,l,h;e=document.createElement("div");d=document.createElement("button");f=document.createElement("div");j=document.createElement("label");l=document.createElement("button");h=document.createElement("button");e.className="item";d.className="chk";j.className="label elps";h.className="btn link";l.className="btn del";e.setAttribute("data-domain",a);e.setAttribute("data-count",b);g&&(d.setAttribute("on",!0),e.setAttribute("on",!0));j.textContent=
a+(c?" ("+b+")":"");d.appendChild(f);e.appendChild(d);e.appendChild(j);e.appendChild(l);e.appendChild(h);l.addEventListener("click",F,!1);h.addEventListener("click",E,!1);e.addEventListener("click",G,!1);return e}function y(a,b,c,g){a=$("list"+a);for(var e,d=document.createDocumentFragment(),f=0;e=b[f];f+=2)e=C(e,b[f+1],c,g),d.appendChild(e);a.appendChild(d)}function B(a,b,c){for(var g=$("list"+b),e,d,f,j=0,l=f=0,h;h=c[l];l++){f=!0;e=h.getAttribute("data-domain");for(var k=0,m;m=g.children[k];k++)if(d=
m.getAttribute("data-domain"),e==d){f=!1;break}else if(e<d){f=parseInt(h.getAttribute("data-count"));j+=f;d=h.firstElementChild.nextElementSibling;d.textContent=0==b?e+" ("+f+")":e;g.insertBefore(h,m);f=!1;break}f&&(f=parseInt(h.getAttribute("data-count")),j+=f,d=h.firstElementChild.nextElementSibling,d.textContent=0==b?e+" ("+f+")":e,g.appendChild(h))}0<j&&(t(a,-j),t(b,j))}function H(){for(var a,b,c=0;2>c;c++)if(a=this.getAttribute("data-d"+c)){a:{b=a;for(var g=$("list0").children,e=void 0,d=0,f=
void 0;f=g[d];d++)if(e=f.getAttribute("data-domain"),e==b){b=f;break a}b=0}b=b?b.parentNode.removeChild(b):C(a,0,0,1);B(0,1,[b])}u()}function n(a){$("shade").style.display=a?"block":"none"}for(var v=-1,x=chrome.i18n.getMessage("cookies").split(";"),q=document.body.innerHTML,k=0,r;r=x[k];k++)q=q.replace(RegExp("t"+(10+k),"gm"),r);document.body.innerHTML=q;$("sel0").addEventListener("click",z,!1);$("sel1").addEventListener("click",z,!1);$("ref").addEventListener("click",m,!1);$("del0").addEventListener("click",
function(){n(1);var a=this.parentElement.nextElementSibling,b=a.querySelectorAll(".item[on]");if(0<b.length){for(var c=[],a=a.getAttribute("data-id"),g,e=0,d=0,f;f=b[d];d++)g=f.getAttribute("data-domain"),c.push(g),e+=parseInt(f.getAttribute("data-count")),f.parentElement.removeChild(f);chrome.extension.sendRequest(JSON.stringify({id:32,v:c}));t(a,-e)}n(0)},!1);$("toc0").addEventListener("click",function(){n(1);A(1,0);u()},!1);$("toc1").addEventListener("click",function(){n(1);A(0,1);u()},!1);m();
x=$("services");q=[{n:"Google | G+, GMail, YouTube, ...",d0:"accounts.google.com",d1:"google.com",i:1},{n:"Facebook",d0:"facebook.com",i:2},{n:"Twitter",d0:"twitter.com",i:3},{n:"Yahoo",d0:"yahoo.com",i:4},{n:"Microsoft | SkyDrive, Live Mail, ...",d0:"login.live.com",d1:"live.com",i:5}];r=document.createDocumentFragment();for(var D=0,p;p=q[D];D++)k=document.createElement("button"),k.className="btn",k.style.cssFloat="left",k.title=p.n,k.setAttribute("data-d0",p.d0),p.d1&&k.setAttribute("data-d1",p.d1),
k.style.backgroundImage="url(i/fav/"+p.i+".png)",k.addEventListener("click",H,!1),r.appendChild(k);x.appendChild(r)}function $(m){return document.getElementById(m)};
