// Extension for Google Chrome - Click&Clean - Copyright (c) 2013 HOTCLEANER.COM - All Rights Reserved
window.addEventListener("load",ccMenu,!1);
function ccMenu(){function C(){var b=this.id;e!=b&&(e&&(document.getElementById(e).className="nav"),e=b,this.className="nav act",y(b))}function y(b){var c,a=document.getElementById("box");if("menu0"==b)c=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,3,"violet","cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,0,"blue",k?"quickscan.png":"extensions.png",k?8:7,3,"violet","downloads.png",9,7,0,"trash1.png",
10,0,"choko","cookie.png",15,7,0,"trash1.png",16,0,"seawave",k?"cleanup.png":"memory.png",k?12:13,3,"violet","security.png",14,0,"carbon","incognito.png",11,0,"teal","report.png",17,0,"magenta","options.png",18,0,"green","updates.png",19,2,["yellow","bluefb","redgp","bluetw","redyt"],["rate32.png","facebook32.png","gplus32.png","twitter32.png","youtube32.png"],20];else if("menu1"==b)c=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",
3,0,"violet","dns.png",4,3,"violet","history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue","version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15];else if("menu2"==b)c=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",
7,3,"teal","devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",11];else if("menu3"==b){c=document.getElementById("donate");if(!c.hasAttribute("init")){for(var h=chrome.i18n.getMessage(b).split(";"),f=c.innerHTML,d=0,e;e=h[d];d++)f=f.replace("t"+(10+d),e);c.innerHTML=f;c.setAttribute("init",!0);document.getElementById("rng").addEventListener("change",v,!1);document.getElementById("ctrb").addEventListener("click",v,!1)}a.style.display="none";c.style.display=
"block";return}d=0;b=chrome.i18n.getMessage(b).split(";");for(var p=document.createDocumentFragment(),m,g,j,q,r,l,n=0;n<c.length;n+=4)q=n/4,m=c[n],j=c[n+1],r=c[n+2],2==m?(g=new Uint8Array(1),crypto.getRandomValues(g),g=g[0]%j.length,q="i"+(q+g),j=j[g],r="i/menu/"+r[g],l=b[c[n+3]+g]):(q="i"+q,r="i/menu/"+r,l=b[c[n+3]]),7>m?(e=0,h=document.createElement("div"),f=document.createElement("div"),g=new Image,j="btn "+j,2<m&&(j+=" wide"),h.id=q,h.className=j,g.className="icn",f.className="txt0",g.dataset.url=
g.src=r,f.textContent=l,h.appendChild(g),h.appendChild(f),p.appendChild(h)):(m=document.createElement("div"),j=document.createElement("div"),g=new Image,g.src=r,m.id=q,m.className="adt a"+e,g.className="icnm",j.className="txt1",j.textContent=l,m.appendChild(g),h.insertBefore(m,f),h.insertBefore(j,f),e++),d++;a.innerHTML="";a.appendChild(p);a.style.display="";document.getElementById("donate").style.display=""}function v(u){var c=u.target.id?u.target:u.target.parentElement,a=c.id;"menu0"==e?(a=parseInt(c.id.slice(1)),
0==a?p(1):1==a?chrome.extension.sendRequest('{"id":0}'):2==a?p(0,c):3==a?chrome.extension.sendRequest('{"id":0}'):4==a?w(0,0):5==a?k?s("http://www.hotcleaner.com/cache-viewer.html","Cache","cache.html"):b(d+"cache"):6==a?p(0,c,"cache"):7==a?s("http://www.hotcleaner.com/clear-browsing-history.html","Clear","history.html"):8==a?p(0,c,"history"):9==a?b(k?"http://www.hotcleaner.com/clickclean-scan-for-malware.html":d+"extensions"):10==a?b(d+"downloads"):11==a?p(0,c,"downloads"):12==a?s("http://www.hotcleaner.com/cookie-wiper.html",
"Cookie","cookies.html"):13==a?p(0,c,"cookies"):14==a?k?chrome.extension.sendRequest('{"id":6,"v":99,"v2":15}'):b(d+"memory"):15==a?k?chrome.extension.sendRequest('{"id":6,"v":201,"v2":0}',function(a){a&&b("http://www.hotcleaner.com/clickclean-app.html")}):(c=navigator.appVersion,a=c.indexOf("Chrome"),28>(0<a?parseInt(c.slice(a+7)):0)?(c=new Image,c.onload=function(){b("http://www.hotcleaner.com/clickclean-app.html")},c.onerror=function(){b("https://chrome.google.com/webstore/detail/pdabfienifkbhoihedcgeogidfmibmhp")},
c.src="chrome-extension://pdabfienifkbhoihedcgeogidfmibmhp/i/16.png"):b("http://www.hotcleaner.com/clickclean-app.html")):16==a?chrome.windows.create({url:void 0,incognito:!0,focused:!0,top:-3,left:-8,width:screen.availWidth+16,height:screen.availHeight+6}):17==a?b("http://hotcleaner.com/security-and-privacy-software-feedback.html"):18==a?chrome.extension.sendRequest('{"id":0}'):19==a?b("http://www.hotcleaner.com/clickclean_chrome_update_checker.html"):20==a?b("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"):
21==a?b("http://www.facebook.com/clickclean"):22==a?b("https://plus.google.com/101494399825495328979/posts"):23==a?b("http://twitter.com/intent/user?screen_name=clickclean"):24==a&&b("http://youtube.com/subscription_center?add_user=YTMoo")):"menu1"==e?(a=parseInt(c.id.slice(1)),0==a?b(d+"plugins"):1==a?b(d+"extensions"):2==a?b(d+"flags"):3==a?b(d+"net-internals"):4==a?b(d+"dns"):5==a?s("http://www.hotcleaner.com/clear-browsing-history.html","Clear","history.html"):6==a?k?s("http://www.hotcleaner.com/cache-viewer.html",
"Cache","cache.html"):b(d+"cache"):7==a?chrome.windows.create({url:"pgen.html",type:"popup",focused:!0,width:350,height:216}):8==a?b(d+"version"):9==a?b("http://chrome.blogspot.com/"):10==a?b(d+(k?"conflicts":"crashes")):11==a?b(d+"policy"):12==a?b("http://googlechromereleases.blogspot.com/"):13==a?b("http://www.chromium.org/developers/calendar"):14==a?b(d+"credits"):15==a&&b("https://code.google.com/p/chromium/issues/list")):"menu2"==e?(a=parseInt(c.id.slice(1)),chrome.extension.sendRequest('{"id":6,"v":99,"v2":'+
a+"}")):"menu3"==e&&("rng"==a?document.getElementById("amnt").textContent="$"+c.value:"ctrb"==a&&b("https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=webmaster@mixesoft.com&item_name=Contribution for Click and Clean&no_note=1&no_shipping=1&country=US&currency_code=USD&amount="+document.getElementById("rng").value));u.stopPropagation()}function w(b,c){chrome.tabs.query(b?{active:!0}:{},function(a){a.forEach(function(h,f){b?chrome.tabs.reload(h.id):f?chrome.tabs.remove(h.id):chrome.tabs.update(h.id,
{url:d+"newtab"});c&&f==a.length-1&&setTimeout(c,500)})})}function p(b,c,a){function d(a){(a||f.p28)&&(new Audio("erased.ogg")).play();setTimeout(function(){e.src="i/menu/done.png";setTimeout(function(){e.src=e.dataset.url},900);x=!1},300)}if(!x)if(x=!0,b)chrome.extension.sendRequest('{"id":4}');else{var f={},e=a?c.previousElementSibling:c.firstElementChild;e.src="i/menu/wipe.gif";a?chrome.extension.sendRequest('{"id":19,"v":{"since":-1},"v2":{"'+a+'":true}}',d):chrome.extension.sendRequest('{"id":3}',
function(a){f=a;f.p0?w(0,function(){chrome.extension.sendRequest('{"id":18}',d)}):chrome.extension.sendRequest('{"id":18}',function(){f.p25?w(1,d):d()})})}}function b(b){chrome.tabs.create({url:b})}function s(b,c,a){chrome.extension.sendRequest('{"id":8,"v":"'+b+'","v2":"'+c+'","v3":"'+a+'"}')}var k=/Win/.test(navigator.platform),x=!1,d=(/Comodo/.test(navigator.appVersion)?"dragon":"chrome")+"://",e="menu0",z=chrome.i18n.getMessage("menu").split(";"),A=document.createDocumentFragment(),B=document.getElementById("menu"),
l;B.id="menu";for(var t=0;t<z.length;t++)if(2!=t||k)l=document.createElement("div"),l.className="nav",l.id="menu"+t,l.textContent=z[t],l.addEventListener("click",C,!1),A.appendChild(l);B.appendChild(A);document.getElementById(e).className="nav act";y(e);document.getElementById("box").addEventListener("click",v,!1)};
