// laobubu.net

var l,c;function rr(r){c=r.data;for(var i=0;i<c.length;i++){var x=document.createElement('tr');x.innerHTML='<td align=right>'+c[i].name+' </td><td><select id="item_'+i+'"></select><img src="reply.gif" title="'+chrome.i18n.getMessage("inputnewvalue")+'" style="cursor:pointer" id="itvv_'+i+'"></td>';l.appendChild(x);$('itvv_'+i).addEventListener('click',update2);var j=$('item_'+i);var x_list=j.options;j.addEventListener('change',update1);var k=c[i].data.replace(/\r/g,'').split('\n');x_list[0]=new Option('- '+chrome.i18n.getMessage("auto")+' -','@AUTO');x_list[1]=new Option('- '+chrome.i18n.getMessage("defaultvalue")+' -','@DEFAULT');x_list[2]=new Option('- '+chrome.i18n.getMessage("remove")+' -','@DELETE');x_list[3]=new Option('- '+chrome.i18n.getMessage("b1ank")+' -','@BLANK');for(b in k){var aa=k[b];var bb=aa;if(aa.indexOf('=')>=1){aa=aa.substr(0,aa.indexOf('='));bb=bb.substr(1+bb.indexOf('='));}
if(bb.length==0)continue;x_list[x_list.length]=new Option(aa,bb);}
var tt=0;x_list[x_list.length]=new Option('- '+chrome.i18n.getMessage("input")+':'+c[i].value,c[i].value);for(;tt<x_list.length;tt++){if(x_list[tt].value==c[i].value){x_list[tt].selected=true;break}}
if(!x_list[x_list.length-1].selected)x_list[x_list.length-1].text='- '+chrome.i18n.getMessage("input")+'?';}}
function loads(){l=$('t');chrome.extension.sendRequest({action:"load_config"},rr);}
function update1(){i=parseInt(event.srcElement.id.substr(5));if(i>=0){var x_list=$('item_'+i).options;if(x_list[x_list.length-1].selected){sStr=prompt(chrome.i18n.getMessage("inputnewvalue"),x_list[x_list.length-1].value);if(sStr!=null){x_list[x_list.length-1].value=sStr;x_list[x_list.length-1].text='- '+chrome.i18n.getMessage("input")+':'+sStr;chrome.extension.sendRequest({action:"update_someone",name:c[i].name,value:sStr},function(r){notice(r.msg)});}}else{chrome.extension.sendRequest({action:"update_someone",name:c[i].name,value:$('item_'+i).value},function(r){notice(r.msg)});}}}
function update2(i){i=parseInt(event.srcElement.id.substr(5));if(i>=0){var x_list=$('item_'+i).options;x_list[x_list.length-1].value=$('item_'+i).value;x_list[x_list.length-1].text='- '+chrome.i18n.getMessage("input")+':'+$('item_'+i).value;x_list[x_list.length-1].selected=true;sStr=prompt(chrome.i18n.getMessage("inputnewvalue"),$('item_'+i).value);if(sStr!=null){x_list[x_list.length-1].value=sStr;x_list[x_list.length-1].text='- '+chrome.i18n.getMessage("input")+':'+sStr;chrome.extension.sendRequest({action:"update_someone",name:c[i].name,value:sStr},function(r){notice(r.msg)});}}}
function notice(s){var o=$('notice');o.innerText=s;o.style.display='';setTimeout("$('notice').style.display='none'",500+100*s.length);}
loads();